version: '3.8'

services:
  postgres:
    image: postgres:12.7
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: itba
      POSTGRES_PASSWORD: itbapass
